id: P004328
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG14512
  title: གངས་གྲོང་གི་རླུང་བུ།
  author: ''
  volumes:
    8685dcc2699a48148a17663caec47611:
      image_group_id: I1KG15658
      title: ''
      volume_number: 1
      total_pages: 316
      base_file: v001.txt
