id: I64DC8422
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T08:43:41+00:00'
last_modified: '2022-06-07T22:01:47.954775+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14512
  title: གངས་གྲོང་གི་རླུང་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    56E6:
      image_group_id: I1KG15658
      title: ''
      total_pages: 316
      order: 1
      base_file: 56E6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
